### ISSUE TITLE
Wrong display message for non-matching milestone

### ISSUE THREAD

**Issue by zoispag** [jusx/mergeable#112]
The message for non-matching milestone in a PR is not displayed.

![image](https://user-images.githubusercontent.com/21138205/49394760-07bdb280-f735-11e8-8af5-7007dc1ffe91.png)

**Comment by jusx** [comment]
Definitely a bug. We will look into addressing it.

**Comment by jusx** [comment]
This is fixed in the last release:
![image](https://user-images.githubusercontent.com/359064/51640484-725ec380-1f18-11e9-91b4-887485da7bfa.png)
