### ISSUE TITLE
Adding option for enforcing title consistency?

### ISSUE THREAD

**Issue by Schachte** [jusx/mergeable#12]
My PR's are _required_ to be prefixed with a certain tag. Is it possible to add the option to say phrase prefix must be present?

**Comment by jusx** [comment]
@Schachte I know you've already closed the issue but in case you didn't already know this. The configuration for `label` takes in regex. Something like this `(^((?!DOC.|FEAT.).)*$)|(WIP)` should enforce the prefixes of `DOC` or `FEAT` in the title as mergeable and still detect `WIP` titles as non-mergeable.

**Comment by Schachte** [comment]
Awesome, thanks for the reponse!
