### ISSUE TITLE
Re-run check is not working

### ISSUE THREAD

**Issue by juandiana** [jusx/mergeable#152]
The [re-run check](https://user-images.githubusercontent.com/1620565/51492409-7c55ba80-1d90-11e9-87fc-ac426a7db645.PNG) capability is not working.

Once you click on it, it'll say that it's pending and it'll stay like that for ever until an event occurs (e.g. a label is added, etc). Only then is the mergeable check re-run.

**Comment by shine2lay** [comment]
@juandiana thanks for creating this ticket. We have not yet implemented the ability to `re-run check`, It is in our road map to add that feature in the future.
My current work around solution is to edit the description, it will trigger `pull_requests.edited` event to mergeable which will re-trigger the checks.

**Comment by jusx** [comment]
Re-run check has been implemented and should be working now -- please refer to #196 for details. Thanks!
