### ISSUE TITLE
Is it possible to install this app on GitHub Enterprise?

### ISSUE THREAD

**Issue by aantono** [jusx/mergeable#166]
Is it possible to install this app on GitHub Enterprise?

**Comment by shine2lay** [comment]
@aantono I am not sure but a quick search showed me that it could be possible. Here is the link : https://platform.github.community/t/installing-integrations-on-github-enterprise/557/13

**Comment by jusx** [comment]
@aantono We do not currently support Enterprise out of the box. A separate instance will have to be deployed with your org with specific settings. Let me know if you're interested in setting one up for your organization. My email is on my profile or join us on [Gitter](https://gitter.im/mergeable-bot/Lobby) and message me.

**Comment by jusx** [comment]
Right now, in order for mergeable to work with GHE, you'd have to deploy your own instance with the environment variable set as per the description here https://github.com/probot/probot/issues/500#issuecomment-381266516

**Comment by jusx** [comment]
Closing this. Let us know if the above solution does not work.
