### ISSUE TITLE
Case sensitivity in approver github usernames

### ISSUE THREAD

**Issue by volksport** [jusx/mergeable#183]
Regarding case sensitivity in approver github usernames: is this intended behavior?

We had a user we added to our mergeable config but did not put the right capitalization for his username, and he was not able to count as an approval.

Since https://github.com/JUSX and https://github.com/jusx both go to the same account, I imagine we don't have to be strict about this?

**Comment by jusx** [comment]
It was not intended.
 
I agree. There is no reason to be case sensitive.
