### ISSUE TITLE
Use CODEOWNERS to provide who needs to be approver

### ISSUE THREAD

**Issue by jayvdb** [jusx/mergeable#24]
https://help.github.com/articles/about-codeowners/

The main limitation on GitHub's implementation is that it ignores approvals by people without write access.

This plugin could use the CODEOWNERS file, and respect it.

**Comment by jusx** [comment]
@jayvdb Interesting. I can see this as being useful! The scope of work to parse the `CODEOWNERS` file and detect the changes of files in a PR is pretty big. 

We want to honor `CODEOWNERS` eventually. For now I will create a separate issue for explicit username list in the YML

**Comment by jusx** [comment]
See #25 for an alternative as per https://github.com/jusx/mergeable/issues/24#issuecomment-389740138

**Comment by jusx** [comment]
@jayvdb Please do let us know how this is working for you. Would love to understand if this helps in streamlining the processes in some of your projects.
