### ISSUE TITLE
Notify Against Consistency in Issues

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#40]
## Context

A standard have been specified for consistencies for Issues.

## Solution
Validate Issues for title, labels, milestones, projects, assignee.

Create a message upon issue.open event.

**Comment by shine2lay** [comment]
I think there is an issue, because when you first open, there will definitely be no label, no milestone, no projects added for sure. This meant that there will be failure. Do you envision this as a reminder?

**Comment by jusx** [comment]
@shine2lay I think you're thinking that this is for PR. This issue is about `issues` though I think we should do the same for `pulls`. In `issues` opened event we should create a comment that displays a "tip" telling the author what he/she missed based on rule-set.

The same should apply for `pulls` -- the intention is that if a team or project sets a particular standards then contributors/members sometimes needs to be reminded of them. Yes, I envision this as a reminder.

So, when someone creates a new issue or pull they don't forget to label, etc.

Longer term vision we want to automate certain things, for example auto-labeling new `issues` as `triage-needed`
