### ISSUE TITLE
Mergeability based on Linting results for JS repos.

### ISSUE THREAD

**Issue by shine2lay** [jusx/mergeable#60]
Context
---
Mergeable will fail if the linting of the source code fails making sure that every code follows the linting rules

Solution 
---
To be discussed in the discussion

**Comment by kevnm67** [comment]
@shine2lay Any chance on adding swiftlint for swift projects?

**Comment by jusx** [comment]
At this moment in time, I feel that something like this may be beyond the scope of mergeable. Linting of code may be better done as part of CI or pre-commit hook... 🤔

**Comment by denis-sokolov** [comment]
This is exactly a workflow that CIs are for. They run custom code to verify the validity of the project’s code and report a status. On top of duplicating the effort, this feature could potentially be very costly. There’s a reason why the CI servers cost money, the verification processes could spend quite a bit of the CPU time.

At the same time Mergeable already includes at least one redundant feature – the number of PR approvals. This is a feature that is built-in in GitHub, yet Mergeable has it as an `approvals`.
![image](https://user-images.githubusercontent.com/113721/52359459-9bb43f00-2a42-11e9-9cfd-d28937640520.png)

**Comment by jusx** [comment]
@denis-sokolov There are a couple iof slight advantage to having the `approvals` validator.

1. If Mergeable is an app installed as a required check, anyone can change approval requirements without being an admin of the repos.

2. This -> #24 

They are edge cases though.

**Comment by jusx** [comment]
Closing. We won't be doing this as it is outside the scope of the project ATM.
