### ISSUE TITLE
When Mergeable Status is success, the description should return all checks that ran

### ISSUE THREAD

**Issue by shine2lay** [jusx/mergeable#69]
Story
---
As a `user`
I would want to `know all the checks Mergeable ran including the status of each run`
so that `I can be assured that all the test I've wanted to ran is done`

Acceptance Criteria 
---
In both `success` and `failure` status for PR,
Show the tests ran in description in the following format :
`Status` Test Description 

where all the failed tests are shown top of the list.

optional ***: we could add details on the test parameter that is passed into each test

**Comment by shine2lay** [comment]
@jusx what do you think about adding details about  test parameters? this way user can identify that their settings are working properly

**Comment by jusx** [comment]
This is implemented in `flex` -- closing.
