### ISSUE TITLE
Complex label check

### ISSUE THREAD

**Issue by srini100** [jusx/mergeable#74]
Is it possible to have a configuration to check the labels in the following way:
(A | B). If B is present then a label with prefix XYZ must also be present. I think the answer is no but just wanted to check. Thanks.

**Comment by jusx** [comment]
@srini100 Currently this is not possible. However we are aware of this limitation and am looking at making this doable in version 2 where the configuration will be much more powerful and flexible across the board.

**Comment by jusx** [comment]
@srini100 version 2 is not till end of Oct. It will cover complex validation across properties of objects (issues, pullRequests, etc) and it's properties (labels, etc). 

However, we are working on enabling complex validations within labels. #75

**Comment by jusx** [comment]
@srini100 Closing this issue since the feature is now deployed. See example AND/OR construct in the PR description #75 

Thanks!

**Comment by srini100** [comment]
Thanks! Will try it out.

**Comment by shine2lay** [comment]
@srini100 hmm.. weird, our test case passed for the exact same scenario, i'll try to debug it later today. Thanks for bringing it up

**Comment by shine2lay** [comment]
Hey @srini100, i found the source of the bug,  you just need to change the `regex: 'lang\\/core|lang\\/c\\+\\+|lang\\/c#'` to `regex: 'lang\/core|lang\/c\+\+|lang\/c#'`. In the test case, I was using template literal so i needed to escape `\`.
